import type { AdvantageTask, Agent, CategorySheet, Mandate } from './types'

export const defaultMandate: Mandate = {
  prompt:
    'Earn on 10,000 USDT. No leverage. Medium risk or lower. Move funds no more than twice a week.',
  goal: 'Earn yield',
  asset: 'USDT',
  capital: 10_000,
  risk: 'Medium',
  leverage: false,
  maxActionsPerWeek: 2,
  allowedProtocols: ['PancakeSwap', 'Venus', 'Lista'],
}

export const agents: Agent[] = [
  {
    id: '8217',
    name: 'YieldRoute',
    category: 'yield',
    recommendation: 'Best fit',
    fit: 87,
    projectedApy: 7.42,
    leverage: 0,
    protocols: ['PancakeSwap', 'Venus', 'Lista'],
    completedMandates: 14,
    disputed: 0,
    capitalObserved: 21_420,
    medianExecutionSeconds: 42,
    lastActive: '3m ago',
    status: 'satisfies',
  },
  {
    id: '6042',
    name: 'SteadyPath',
    category: 'yield',
    recommendation: 'Safer',
    fit: 82,
    projectedApy: 6.18,
    leverage: 0,
    protocols: ['Venus', 'Lista'],
    completedMandates: 8,
    disputed: 0,
    capitalObserved: 12_610,
    medianExecutionSeconds: 55,
    lastActive: '11m ago',
    status: 'satisfies',
  },
  {
    id: '1938',
    name: 'AggroMax',
    category: 'yield',
    recommendation: 'Cheaper',
    fit: 79,
    projectedApy: 8.91,
    leverage: 2,
    protocols: ['PancakeSwap', 'Venus', 'Lista', 'Aave'],
    completedMandates: 27,
    disputed: 2,
    capitalObserved: 88_930,
    medianExecutionSeconds: 31,
    lastActive: '1m ago',
    status: 'violates',
    violation: 'Uses 2× leverage',
  },
]

export const advantageTasks: AdvantageTask[] = [
  {
    id: 'A-01',
    task: 'Stablecoin yield route selection',
    category: 'Yield optimisation',
    agentTime: '2.9864 sec',
    baselineTime: '290.004 sec',
    agentCost: '0.1 test U hire',
    baselineCost: '$0 observed',
    qualityDelta: '2/10 → 10/10',
    evidence: 'Job #642 · independent provider · completed',
  },
  {
    id: 'A-02',
    task: 'BNB/USDT grid plan safety review',
    category: 'Trading',
    agentTime: '0.4796 sec',
    baselineTime: '233.650 sec',
    agentCost: '0.1 test U hire',
    baselineCost: '$0 observed',
    qualityDelta: '4/10 → 10/10',
    evidence: 'Job #644 · independent provider · completed',
  },
  {
    id: 'A-03',
    task: 'Venus health-factor intervention',
    category: 'Security / risk monitoring',
    agentTime: '0.4777 sec',
    baselineTime: '226.700 sec',
    agentCost: '0.1 test U hire',
    baselineCost: '$0 observed',
    qualityDelta: '8/10 → 10/10',
    evidence: 'Job #666 · independent provider · completed',
  },
]

export const categorySheets: CategorySheet[] = [
  {
    category: 'liquidity',
    eyebrow: 'LP REBALANCING',
    agent: 'RangeGuard',
    mandate: 'Keep BNB/USDT in range · max 2 rebalances/day',
    fit: 91,
    metrics: [
      { label: 'Range uptime', value: '96.8%', source: 'HISTORICAL SAMPLE' },
      { label: 'Net fees', value: '+$184.20', source: 'HISTORICAL SAMPLE' },
      { label: 'Gas drag', value: '0.14%', source: 'DERIVED SAMPLE' },
      { label: 'Rebalance frequency', value: '1.3 / day', source: 'HISTORICAL SAMPLE' },
      { label: 'IL vs HODL', value: '-0.82%', source: 'DERIVED SAMPLE' },
    ],
    riskRule: 'Reject if gas drag erases >20% of fees or daily action cap is exceeded.',
  },
  {
    category: 'grid',
    eyebrow: 'GRID TRADING',
    agent: 'GridPilot',
    mandate: 'Trade BNB/USDT · max drawdown 5% · 12 fills/day',
    fit: 88,
    metrics: [
      { label: 'Net PnL after fees', value: '+4.26%', source: 'HISTORICAL SAMPLE' },
      { label: 'Max drawdown', value: '3.18%', source: 'DERIVED SAMPLE' },
      { label: 'Profit factor', value: '1.71', source: 'DERIVED SAMPLE' },
      { label: 'Fill rate', value: '83.4%', source: 'HISTORICAL SAMPLE' },
      { label: 'Market regime', value: 'Ranging', source: 'DERIVED SAMPLE' },
    ],
    riskRule: 'Pause when drawdown reaches 4.5%; hard reject at the 5% mandate limit.',
  },
  {
    category: 'yield',
    eyebrow: 'YIELD OPTIMISATION',
    agent: 'YieldRoute',
    mandate: 'Earn on 10,000 USDT · no leverage · medium risk',
    fit: 87,
    metrics: [
      { label: 'Realised net APY', value: '7.42%', source: 'DERIVED SAMPLE' },
      { label: 'Protocol switches', value: '1 / week', source: 'HISTORICAL SAMPLE' },
      { label: 'Gas cost', value: '$0.27', source: 'HISTORICAL SAMPLE' },
      { label: 'Risk exposure', value: 'Medium', source: 'DERIVED SAMPLE' },
      { label: 'Time in position', value: '99.2%', source: 'HISTORICAL SAMPLE' },
    ],
    riskRule: 'Reject leverage, unallowlisted protocols, or more than two actions per week.',
  },
  {
    category: 'health',
    eyebrow: 'HEALTH FACTOR MONITORING',
    agent: 'LiqShield',
    mandate: 'Keep Venus health factor above 1.8 · no new borrowing',
    fit: 94,
    metrics: [
      { label: 'Minimum HF', value: '1.92', source: 'HISTORICAL SAMPLE' },
      { label: 'Warning lead time', value: '4m 18s', source: 'DERIVED SAMPLE' },
      { label: 'Response latency', value: '6.2s', source: 'HISTORICAL SAMPLE' },
      { label: 'Interventions', value: '7 / 7', source: 'HISTORICAL SAMPLE' },
      { label: 'False alerts', value: '0', source: 'DERIVED SAMPLE' },
    ],
    riskRule: 'Only repay or add collateral; never borrow or increase leverage.',
  },
]
