import type { AdvantageTask, Agent, CategorySheet, Mandate } from './types'

export const defaultMandate: Mandate = {
  prompt:
    'Earn on 10,000 USDT. No leverage. Medium risk or lower. Move funds no more than twice a week.',
  goal: 'Earn yield',
  asset: 'USDT',
  capital: 10_000,
  risk: 'Medium',
  leverage: false,
  maxActionsPerWeek: 2,
  allowedProtocols: ['PancakeSwap', 'Venus', 'Lista'],
}

export const agents: Agent[] = [
  {
    id: '8217',
    name: 'YieldRoute',
    category: 'yield',
    recommendation: 'Best fit',
    fit: 0,
    projectedApy: null,
    leverage: 0,
    protocols: ['PancakeSwap', 'Venus', 'Lista'],
    completedMandates: null,
    disputed: null,
    capitalObserved: null,
    medianExecutionSeconds: null,
    lastActive: null,
    dataQuality: 'unverified-sample',
    status: 'satisfies',
  },
  {
    id: '6042',
    name: 'SteadyPath',
    category: 'yield',
    recommendation: 'Safer',
    fit: 0,
    projectedApy: null,
    leverage: 0,
    protocols: ['Venus', 'Lista'],
    completedMandates: null,
    disputed: null,
    capitalObserved: null,
    medianExecutionSeconds: null,
    lastActive: null,
    dataQuality: 'unverified-sample',
    status: 'satisfies',
  },
  {
    id: '1938',
    name: 'AggroMax',
    category: 'yield',
    recommendation: 'Cheaper',
    fit: 0,
    projectedApy: null,
    leverage: 2,
    protocols: ['PancakeSwap', 'Venus', 'Lista', 'Aave'],
    completedMandates: null,
    disputed: null,
    capitalObserved: null,
    medianExecutionSeconds: null,
    lastActive: null,
    dataQuality: 'unverified-sample',
    status: 'violates',
    violation: 'Uses 2× leverage',
  },
]

export const advantageTasks: AdvantageTask[] = [
  {
    id: 'A-01',
    task: 'Stablecoin yield route selection',
    category: 'Yield optimisation',
    agentTime: '2.9864 sec',
    baselineTime: '290.004 sec',
    agentCost: '0.1 test U hire',
    baselineCost: '$0 observed',
    qualityDelta: '2/10 → 10/10',
    evidence: 'Job #642 · independent provider · completed',
  },
  {
    id: 'A-02',
    task: 'BNB/USDT grid plan safety review',
    category: 'Trading',
    agentTime: '0.4796 sec',
    baselineTime: '233.650 sec',
    agentCost: '0.1 test U hire',
    baselineCost: '$0 observed',
    qualityDelta: '4/10 → 10/10',
    evidence: 'Job #644 · independent provider · completed',
  },
  {
    id: 'A-03',
    task: 'Venus health-factor intervention',
    category: 'Security / risk monitoring',
    agentTime: '0.4777 sec',
    baselineTime: '226.700 sec',
    agentCost: '0.1 test U hire',
    baselineCost: '$0 observed',
    qualityDelta: '8/10 → 10/10',
    evidence: 'Job #666 · independent provider · completed',
  },
]

export const categorySheets: CategorySheet[] = [
  {
    category: 'liquidity',
    eyebrow: 'LP REBALANCING',
    agent: 'RangeGuard',
    mandate: 'Keep BNB/USDT in range · max 2 rebalances/day',
    fit: 100,
    evidenceStatus: 'live-read-only',
    metrics: [
      { label: 'Identity', value: 'Agent #1804', source: 'ERC-8004 · BSC' },
      { label: 'Market source', value: 'PancakeSwap BNB/USDT', source: 'LIVE DEXSCREENER' },
      { label: 'Decision', value: 'Bounded LP range', source: 'LIVE ON REQUEST' },
      { label: 'Transaction authority', value: 'None', source: 'READ ONLY' },
      { label: 'Evidence', value: 'SHA-256 JSON', source: 'DOWNLOADABLE' },
    ],
    riskRule: 'Reject if gas drag erases >20% of fees or daily action cap is exceeded.',
  },
  {
    category: 'grid',
    eyebrow: 'GRID TRADING',
    agent: 'GridPilot',
    mandate: 'Trade BNB/USDT · max drawdown 5% · 12 fills/day',
    fit: 100,
    evidenceStatus: 'paper-only',
    metrics: [
      { label: 'Identity', value: 'Agent #1805', source: 'ERC-8004 · BSC' },
      { label: 'Market source', value: 'PancakeSwap BNB/USDT', source: 'LIVE DEXSCREENER' },
      { label: 'Decision', value: 'Grid + hard stop', source: 'LIVE ON REQUEST' },
      { label: 'Track record', value: '30-day paper test', source: 'HASH VERIFIABLE' },
      { label: 'Hire evidence', value: 'Job #644', source: 'ERC-8183 · COMPLETED' },
    ],
    riskRule: 'Pause when drawdown reaches 4.5%; hard reject at the 5% mandate limit.',
  },
  {
    category: 'yield',
    eyebrow: 'YIELD OPTIMISATION',
    agent: 'YieldRoute',
    mandate: 'Earn on 10,000 USDT · no leverage · medium risk',
    fit: 100,
    evidenceStatus: 'verified-onchain',
    metrics: [
      { label: 'Identity', value: 'Agent #1806', source: 'ERC-8004 · BSC' },
      { label: 'Yield source', value: 'Pancake · Venus · Lista', source: 'LIVE DEFILLAMA' },
      { label: 'Decision', value: 'Highest compliant APY', source: 'LIVE ON REQUEST' },
      { label: 'Transaction authority', value: 'None', source: 'READ ONLY' },
      { label: 'Hire evidence', value: 'Job #642', source: 'ERC-8183 · COMPLETED' },
    ],
    riskRule: 'Reject leverage, unallowlisted protocols, or more than two actions per week.',
  },
  {
    category: 'health',
    eyebrow: 'HEALTH FACTOR MONITORING',
    agent: 'LiqShield',
    mandate: 'Keep Venus health factor above 1.8 · no new borrowing',
    fit: 100,
    evidenceStatus: 'live-read-only',
    metrics: [
      { label: 'Identity', value: 'Agent #1807', source: 'ERC-8004 · BSC' },
      { label: 'Protocol source', value: 'Venus Comptroller', source: 'LIVE ETH_CALL' },
      { label: 'Decision', value: 'Pinned-block risk', source: 'LIVE ON REQUEST' },
      { label: 'Transaction authority', value: 'None', source: 'READ ONLY' },
      { label: 'Hire evidence', value: 'Job #666', source: 'ERC-8183 · COMPLETED' },
    ],
    riskRule: 'Only repay or add collateral; never borrow or increase leverage.',
  },
]
